language: r
sudo: false
cache: packages
dist: trusty

r:
  - oldrel
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov()'

r_check_args: "--as-cran"

notifications:
  email:
    on_success: change
    on_failure: change