language: r
sudo: false
cache: packages
dist: trusty

r:
 - release

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
